---


- hosts: all
  become: true
  tasks:

  - name: install the apache package and add php support for apache
    package:
      name: 
        - "{{ apache_package }}"
        - "{{ php_package }}"
      state: latest
      update_cache: yes




# - hosts: all
#   become: true
#   tasks:

#   - name: update repository index
#     apt: 
#       update_cache: yes
#     when: ansible_distribution in ["Ubuntu", "Debian"]

#   - name: install the apache2 package
#     apt:
#       name: apache2
#       state: latest
#     when: ansible_distribution == "Ubuntu"

#   - name: add php support for apache
#     apt:
#       name: libapache2-mod-php
#       state: latest
#     when: ansible_distribution == "CentOS" and ansible_distribution_version == "8.2"


#   - name: update repository index
#     dnf: 
#       update_cache: yes
#     when: ansible_distribution == "CentOS"

#   - name: install the apache2 package
#     dnf:
#       name: httpd
#       state: latest
#     when: ansible_distribution == "CentOS"

#   - name: add php support for apache
#     dnf:
#       name: php
#       state: latest
#     when: ansible_distribution == "CentOS"
